//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public int IssueID { get; set; }
        public string Issuer { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
