<%@ Page Title="" Language="C#" MasterPageFile="~/Optimus.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="EntityFramework.Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  
    <p style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; line-height: 1.1em; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: inherit;">
        About Us</p>
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; line-height: 23.1000003814697px; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Optimus is designed to help global organizations address their information needs. The world of information is changing and so are the methods of managing it. We provide outsourced technology services to mid-sized organizations who&nbsp;have different needs than Fortune 500 companies. Optimus is designed to meet these&nbsp;specific&nbsp;needs.</p>
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; line-height: 23.1000003814697px; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        The demand for outsourced technology services is increasing as organizations seek to increase their efficiency. This trend has been improved through advancements in technology and telecommunications that now allow outsourcing services to offer seamless services all over the globe.</p>
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; line-height: 23.1000003814697px; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Though outsourcing is a maturing market, mid-sized software companies and enterprises often struggle to find a reliable, nimble, and capable outsourcing vendor. Optimus has the right mix of size, flexibility, and experience to provide high quality outsourcing solutions to mid-sized software companies and enterprises.</p>
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; line-height: 23.1000003814697px; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Optimus is headquartered in Vancouver, Canada and has delivery centers in Canada and India. The founders of Optimus have extensive experience running large global outsourcing companies.</p>
    <h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; line-height: 1.1em; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: inherit;">Optimus Core Values:</strong></h3>
    <ul style="box-sizing: border-box; margin: 0px 0px 20px 7px; padding: 0px; border: 0px rgb(225, 225, 225); font-family: 'Open Sans', HelveticaNeue, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; line-height: 23.1000003814697px; vertical-align: baseline; list-style: disc outside; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">Universal Entrepreneurial Spirit</li>
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">Absolute Customer Satisfaction</li>
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">Self Led</li>
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">High Intellectual Capital</li>
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">Work Life Integration</li>
        <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-indent: 0px;">Celebrate Success</li>
    </ul>
    <p>
        &nbsp;</p>
</asp:Content>
